/* File generated with Shader Minifier 1.1.4
 * http://www.ctrl-alt-test.fr
 */
#ifndef SHADER_CODE_H_
# define SHADER_CODE_H_

const char *fragment_glsl =
 "uniform sampler3D B;"
 "vec2 v(vec3 v,vec3 x,float m,out vec3 r,float y)"
 "{"
   "float g=1.,z=10000.,i,t,f,s;"
   "vec3 d,p;"
   "for(float l=0;l<20;++l)"
     "{"
       "disc(l,d,p,s,y);"
       "i=dot(d-v,p)/dot(x,p);"
       "if(i>0)"
         "{"
           "t=i*m;"
           "g*=smoothstep(-t,t,f=length(v+x*i-d)-s);"
           "if(i<z&&f<0)"
             "z=i,r=p*-sign(dot(p,x));"
         "}"
     "}"
   "return vec2(g,z);"
 "}"
 "mat2 v(float y)"
 "{"
   "return mat2(cos(y),sin(y),sin(y),-cos(y));"
 "}"
 "void main()"
 "{"
   "gl_FragColor.x=pow(1-min(length(vec3(gl_PointCoord.xy,gl_TexCoord[0].y)-.5)*2,1),2)*gl_TexCoord[0].x;"
   "if(gl_TexCoord[0].z==3)"
     "{"
       "float y=gl_TexCoord[0].x/1000,x=y,g=.4,p=(y-23)/30,m=-.1,z,r=1,t=0,f=0;"
       "vec3 i=vec3(0.,-.14,2.1),d=normalize(vec3(gl_FragCoord.xy/360-vec2(1.778,1),-1.6)),s,o,l=vec3(1,1,2)/2.45;"
       "if(y>65)"
         "y-=65,i=vec3(0.,-.14,1.82),l=vec3(2,4,1)/4.58,m=.5,g=.6,p=y/75.;"
       "else"
         " if(y>46)"
           "y-=46,i=vec3(0.,.1,2.),l=vec3(1,4,2)/4.58,p=g=m=0;"
       "i.yx*=v(m);"
       "d.yx*=v(m);"
       "i.yz*=v(g);"
       "d.yz*=v(g);"
       "i.xz*=v(p);"
       "d.xz*=v(p);"
       "gl_FragColor=vec4(.5+.5*d.y)/2;"
       "vec3 c=-(i-1)/d,e=-(i+1)/d,a=min(c,e),n=max(c,e),C=vec3(0,1,0)/32;"
       "vec2 u=vec2(max(0,max(max(a.x,a.y),a.z)),min(min(n.x,n.y),n.z)),F=abs(gl_FragCoord.xy/vec2(640,360)-1);"
       "g=v(i,d,0,s,x).y;"
       "if(u.x<u.y)"
         "{"
           "for(float h=0;h<1&&t<.5;h+=1./600)"
             "z=mix(u.x,u.y,h),t=texture(B,(i+1+d*z)/2).x;"
           "if(t>.5&&z<g)"
             "c=(i+1+d*z)/2,c=reflect(d,e=normalize(vec3(texture(B,c-C.yxx).x-texture(B,c+C.yxx).x,texture(B,c-C).x-texture(B,c+C).x,texture(B,c-C.xxy).x-texture(B,c+C.xxy).x))),t=mix(.1,.9,pow(min(dot(e,d)+1,1),2)),r=1-t,i+=d*z,g=v(i,d=refract(d,e,.9),0,s,x).y,f=(.5+c.y/2+step(-c.y,.001))/2*t;"
         "}"
       "if(g<1000.)"
         "t=.004+v(i+=d*(g-1e-05),l,.3,o,x).x*max(0,dot(s,l)),t+=.1*v(i,-d,.6,o,x).x*max(0,dot(s,-d)),gl_FragColor=r*vec4(t+mix(.02,1.,v(i,C*32,2.,o,x).x)*max(0,s.y))/4*(1-texture(B,(i+1)/2).x/2*step(length(pow(i*i,1/C.yyy)),.1));"
       "gl_FragColor=pow(gl_FragColor+f,vec4(1,1.4,1.3,1))*min(1-smoothstep(0,5,x-83),y);"
       "gl_FragColor=sqrt((gl_FragColor/=gl_FragColor*.56+.45)*(1.43-dot(F*F,F)/2));"
     "}"
 "}";

const char *vertex_glsl =
 "void main()"
 "{"
   "float i=floor(gl_Vertex.x/7),g=mod(gl_Vertex.x,7.),v=gl_MultiTexCoord0.x/1000,y=v;"
   "v-=clamp((v-73.5)*18,0,8.5);"
   "vec3 c=vec3(-.7,.95,.1),d=(1.+cos(i*6)/2)*vec3(cos(i*5)*.15,cos(i*7)*.15,sin(i*5)*.15)*mix(1.1,1.5,.5+cos(i*99.)/2)*2.4,t=vec3(0,-1.2,0)*4*2*mix(.7,1.,.5+cos(i*79.)/2)*1.2,x,s;"
   "v-=25;"
   "if(v>40)"
     "v-=40,c*=0,t*=.001;"
   "else"
     " if(v>21)"
       "v-=21,c=vec3(cos(i*5)*.8,.9,cos(i*7)*.1),d*=0;"
   "float m=max(0,v*.1-mod(i*.2+sin(i*7)*.3,3.)/3),p;"
   "for(float z=0;z<32;++z)"
     "{"
       "float r=m;"
       "vec3 B,f;"
       "for(float l=0;l<20;++l)"
         "{"
           "disc(l,x,s,p,y);"
           "float C=d.y+dot(d.xz,s.xz)/s.y,e=C*C-t.y*dot(c-x,s)/s.y*4,a=(-C-sqrt(e))/t.y/2;"
           "if(e>0)"
             "{"
               "vec3 o=c+d*a+t*a*a;"
               "if(a>0&&a<r&&length(o-x)<p)"
                 "B=o,f=reflect(d+t*a*2,s)*.7,r=a;"
             "}"
         "}"
       "if(m>r)"
         "c=B,d=f,m-=r;"
     "}"
   "x=c+d*m+t*m*m;"
   "p=floor((x.z+1)*32)+g-4;"
   "gl_TexCoord[0]=vec4(step(length(pow(abs(x),vec3(32))),.1),(g-fract((x.z+1)*32))/7,0,0);"
   "gl_Position.xy=(x.xy+1)/8+vec2(mod(p,8),floor(p/8))/4-1;"
 "}";

const char *version_glsl =
 "#version 130\n";

const char *discfunc_glsl =
 "void disc(float i,out vec3 v,out vec3 x,out float d,float y)"
 "{"
   "y-=clamp((y-73.5)*18,0,8.5);"
   "v=vec3(-cos(i),-.8+i/25,sin(i*2))*1.5;"
   "v.zx*=max(0,1-i/20);"
   "x=vec3(.1,1,0);"
   "d=(.45+sin(i*7)*.15)*clamp(y+i-24,0,1);"
   "if(y>65)"
     "{"
       "y-=65;"
       "d=.34+sin(i*97)*.3;"
       "float c=smoothstep(0,1,1.-exp(-y/8.))*2;"
       "v=normalize(vec3(-cos(i*5),-1+i/33,sin(i)))*(.5+c/5);"
       "x=v-vec3(0,-.1+c/8,0);"
     "}"
   "else"
     " if(y>46)"
       "y-=46,v*=vec3(.7,1,.01),v.y+=.4,x=vec3(cos(i*5)*.1,1,.1);"
   "x=normalize(x);"
 "}";

#endif // SHADER_CODE_H_
